services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sipesa_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    environment:
      APP_NAME: SiPeSa
      APP_ENV: production
      APP_KEY: ${APP_KEY:-base64:g8y6SkTtn0bRi4qs0R0uZN1I6ckhBtoEesyddDG6DkQ=}
      APP_DEBUG: "false"
      APP_URL: ${APP_URL:-https://cherome.my.id}
      APP_TIMEZONE: Asia/Jakarta
      APP_LOCALE: id
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-sipesa}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      SESSION_DRIVER: file
      SESSION_LIFETIME: "120"
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
    volumes:
      - uploads_data:/var/www/html/storage/app/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sipesa_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sipesa}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  uploads_data:
